### ISSUE TITLE
Idea: Should we include control layout boundary indication line?

### ISSUE THREAD

**Issue by chigy** [chigy/winui-redline#11]
Looking at this image Tammy added in checkin, I wonder if we need to specify where the control's layout bound is because some of the measurement seems to measure out in an empty space and may not be clear what it is measuring?

![image](https://user-images.githubusercontent.com/22958680/61736762-a6863600-ad3b-11e9-91b1-e2fafdba7f27.png)

**Comment by kikisaints** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/6964369/61737536-43959e80-ad3d-11e9-8605-19fa506c7a74.png)

**Comment by chigy** [comment]
@kikisaints , yes, something like that.
@teaP , will this work for your slider question, too?

**Comment by teaP** [comment]
Like.... this?
![image](https://user-images.githubusercontent.com/30241445/61741471-d9cdc280-ad45-11e9-9829-920d34279e37.png)

**Comment by chigy** [comment]
@teaP , let's go with that for now. @kikisaints , what do you think? Any feedback?

**Comment by kikisaints** [comment]
I like @teaP's better, less intrusive and more legible with the redlines.

**Comment by chigy** [comment]
This was resolved.
