### ISSUE TITLE
There's extra layer box for color redline

### ISSUE THREAD

**Issue by chigy** [chigy/winui-redline#18]
@kaiguo , I think Tammy has a conditional code to remove the inner box? Yours is showing two boxes.

![image](https://user-images.githubusercontent.com/22958680/61835214-b54e1500-ae2f-11e9-93a3-e30e2608da42.png)

**Comment by kaiguo** [comment]
@chigy Yeah, I intentionally added inner lines, I thought it would be easier to figure out what the redline is pointing at this way, but I can remove it if they are not needed : )

**Comment by chigy** [comment]
@kaiguo , I think for the color this is more confusing than not having it. Can you remove the dotted line altogether for the color one? That's more for measurement.

**Comment by chigy** [comment]
On the second thought, let's keep it. I see the reason why you added those and maybe good thing, but will have to have a closer look.
