### ISSUE TITLE
Ideal Checkbox state visual

### ISSUE THREAD

**Issue by chigy** [chigy/winui-redline#6]
Sharing the ideal checkbox state visual comp that matches the visual comp we use to design.

![image](https://user-images.githubusercontent.com/22958680/61553881-5f810380-aa10-11e9-8676-d88dd2a152fb.png)

**Comment by kikisaints** [comment]
@chigy I think I recreated this layout okay enough - if you think so too can you close this issue?

**Comment by chigy** [comment]
With pleasure!
